products_list:
    path: /
    defaults: { _controller: RabotaBundle:Default:getProductList}

order_new:
    path: /order/new
    defaults: { _controller: RabotaBundle:Default:newOrder}

product_new:
    path: /product/new
    defaults: { _controller: RabotaBundle:Default:newProduct}

order_list:
    path: /order-list
    defaults: { _controller: RabotaBundle:Default:getOrderList}

order_del:
    path: /ajax/order/{id}/del
    defaults: { _controller: RabotaBundle:Default:delOrder}

product_del:
    path: /ajax/product/{id}/del
    defaults: { _controller: RabotaBundle:Default:delProduct}

product_edit:
    path: /ajax/product/{id}/edit
    defaults: { _controller: RabotaBundle:Default:editProduct}

order_show:
    path: /order/{id}
    defaults: { _controller: RabotaBundle:Default:showOrder}

