rabota_homepage:
    path:     /rabota/
    defaults: { _controller: RabotaBundle:Default:index }

test_page:
    path: /rabota/rabota/
    defaults: { _controller: RabotaBundle:Default:rabota }

save_order:
      path: /order-save
      defaults: { _controller: RabotaBundle:Default:saveOrder}

save_product:
      path: /product-save
      defaults: { _controller: RabotaBundle:Default:saveProduct}

products_list:
    path: /product-list
    defaults: { _controller: RabotaBundle:Default:getProductList}

order_list:
    path: /order-list
    defaults: { _controller: RabotaBundle:Default:getOrderList}

order_new:
    path: /order/new
    defaults: { _controller: RabotaBundle:Default:newOrder}

add_product_to_order:
    path: /add-product
    defaults: { _controller: RabotaBundle:Default:addProductToOrder}
